package app

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"github.com/julienschmidt/httprouter"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	"html/template"
	"io/ioutil"
	"log"
	"net/http"
)

/*
** contains handler fuctions which do not require admin account
** contains fuctions to interact with OAuth2
 */

var confOAuth2 *oauth2.Config

var state string

func init() {

	// doesen't needs to be called explicitly
	// configures OAuth2 and Mysql

	var credOAuth2 CredentialOAuth2
	var credMysql CredentialMysql

	fileOAuth2, err := ioutil.ReadFile("./credOAuth2.json")
	if err != nil {
		log.Fatalf("Error while reading oauth2 config file.\nError: %v\n", err.Error())
	}
	json.Unmarshal(fileOAuth2, &credOAuth2)

	confOAuth2 = &oauth2.Config{

		// presently set through account nishchayparashar98@gmail.com
		ClientID:     credOAuth2.Cid,
		ClientSecret: credOAuth2.Csecret,

		// change redirect on production server
		RedirectURL: "http://127.0.0.1:8080/options",

		Scopes: []string{
			"https://www.googleapis.com/auth/userinfo.email",
		},
		Endpoint: google.Endpoint,
	}

	fileMysql, err := ioutil.ReadFile("./credMysql.json")
	if err != nil {
		log.Fatalf("Error while reading oauth2 config file.\nError: %v\n", err.Error())
	}
	json.Unmarshal(fileMysql, &credMysql)

	connectionString := fmt.Sprintf("%s:%s@/%s?charset=utf8&parseTime=True&loc=Local",
		credMysql.DBUsername,
		credMysql.DBPassword,
		credMysql.DBName)

	DB.db, err = gorm.Open("mysql", connectionString)
	if err != nil {
		log.Fatal("Could not open database : ", err.Error())
	}

	state = randState()

}

func randState() string {

	// generates random string

	b := make([]byte, 32)
	rand.Read(b)
	return base64.StdEncoding.EncodeToString(b)
}

func Index(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	var indexTemplate *template.Template
	indexTemplate = template.Must(template.ParseGlob("templates/index.html"))
	indexTemplate.Execute(w, nil)

}

func LoginHandler(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	// calls Google OAuth2 api endpoint on the provided configuration

	http.Redirect(w, r, confOAuth2.AuthCodeURL(state), 302)
}

func Options(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	// callback after user is authenticated via OAuth2

	// checks if the state appended to callback url is same as generated by app
	// thus ensures the callback is not from a man in the middle
	if r.FormValue("state") != state {
		http.Error(w, "Possibly malacious/fake callback redirect", http.StatusBadRequest)
		log.Printf("Possibly malacious/fake callback redirect. Random state does not match\nError: %v\n", http.StatusBadRequest)
		return
	}

	// call Exchange on conf to get token from Google OAuth2 api
	// pass code recieved as callback url parameter
	tok, err := confOAuth2.Exchange(oauth2.NoContext, r.FormValue("code"))
	if err != nil {
		http.Error(w, "Could not exchange code for google token", http.StatusBadRequest)
		log.Printf("Could not exchange code for google token.\nError: %v\n", err.Error())
		return
	}

	// authenticate the google token obtained by calling endpoint
	// provided by google for token authentication
	check, err := http.Get("https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=" + tok.AccessToken)
	if err != nil {
		http.Error(w, "Google token not authentic", http.StatusBadRequest)
		log.Printf("Google token not authentic.\nError: %v\n", err.Error())
		return
	}
	defer check.Body.Close()

	// use token to get user info
	client := confOAuth2.Client(oauth2.NoContext, tok)
	info, err := client.Get("https://www.googleapis.com/oauth2/v3/userinfo")
	if err != nil {
		http.Error(w, "User info could not be obtained", http.StatusBadRequest)
		log.Printf("User info could not be obtained.\nError: %v\n", err.Error())
		return
	}
	defer info.Body.Close()
	data, _ := ioutil.ReadAll(info.Body)

	var googTok GoogleToken

	json.Unmarshal(data, &googTok)

	// check if user has a verified gmail account
	if googTok.EmailVerified == false {
		http.Redirect(w, r, "https://myaccount.google.com/", 302)
		return
	}

	// set google token as cookie
	SetCookieHandler(&googTok, w)

	log.Printf("%v logged in using account %v", googTok.Name, googTok.Email)

	http.Redirect(w, r, "/", 302)

}

func LogoutHandler(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	// clears cookie logs out user

	ClearCookieHandler(w)
	http.Redirect(w, r, "/", 302)

}

func MakeAccessRequest(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	// make request to get access to server user wants to work on

	// request contains user's ssh key and message describing the project
	// they are working on
	type Receive struct {
		SshKey  string `json:"ssh_key"`
		Message string `json:"message"`
	}

	var response Response

	decoder := json.NewDecoder(r.Body)
	var receive Receive
	err := decoder.Decode(&receive)
	if err != nil {
		http.Error(w, "Error reading the received request", http.StatusBadRequest)
		log.Printf("Error reading the received request.\nError: %v\n", err.Error())
		return
	}

	googTok := ReadCookieHandler(w, r)

	if googTok.Email == "" {
		response = Response{
			false,
			"User not authenticated",
		}
	} else {

		var accessRequest AccessRequest

		// register new request if it does not already exists
		notFoundErr := DB.db.Debug().Where("email = ?", googTok.Email).First(&accessRequest).Error
		if notFoundErr != nil {
			accessRequest = AccessRequest{
				Name:    googTok.Name,
				Email:   googTok.Email,
				Message: receive.Message,
				SshKey:  receive.SshKey,
			}

			DB.db.Create(&accessRequest)

			response = Response{
				true,
				"New request sent",
			}
		} else {
			response = Response{
				false,
				"Request already exists",
			}
		}

	}

	json, err := json.Marshal(response)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(json)

}

func MakeAdminRequest(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {

	// make request to get admin privileges for DAMN portal

	var response Response

	googTok := ReadCookieHandler(w, r)

	if googTok.Email == "" {
		response = Response{
			false,
			"User not authenticated",
		}
	} else {

		var adminRequest AdminRequest

		// register new request if it does not already exists
		notFoundErr := DB.db.Debug().Where("email = ?", googTok.Email).First(&adminRequest).Error
		if notFoundErr != nil {
			adminRequest = AdminRequest{
				Name:  googTok.Name,
				Email: googTok.Email,
			}

			DB.db.Create(&adminRequest)

			response = Response{
				true,
				"New request sent",
			}
		} else {
			response = Response{
				false,
				"Request already exists",
			}
		}

	}

	json, err := json.Marshal(response)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(json)

}
